lxmls/sequences/crf_batch.py

Hello,
this commit just fix a little mistake in one import of crf_batch.py
Cheers

Fix import error in crf_batch.py

---

lxmls/sequences/hmm.py

Simpler code that directly translates the formulas given in the guide

no need to use np.tile

---

lxmls/deep_learning/SemEvalTwitter.py
lxmls/labs/day6_Twitter.py

added evaluation with the SemEval metric; added example with pre-trained embeddings; added example of fixing embedding layer when training

Twitter Sentiment Analysis

---

lxmls/sequences/sequence_classification_decoder.py

Give a contract of the funcion (stored variables they must use and what they have to return.
Give some hints for the implementation ( and direct references to the guide)

Update sequence_classification_decoder.py with some hints and references to the guide

---

solve.py

The comma is missed, does not compile

Fix bug in solve.py

---

lxmls/readers/simple_data_set.py

Loader tried to index numpy array with float, casted it to int.

Fixed bug with simple_data_set.py loader

---

labs/notebooks/learning_structured_predictors/exercise_1.ipynb
labs/notebooks/learning_structured_predictors/exercise_2.ipynb
labs/notebooks/learning_structured_predictors/exercise_3.ipynb
labs/notebooks/learning_structured_predictors/exercise_4.ipynb

Adding exercices for the sturctured predictors part

adding notebooks for structured_predictors

---

lxmls/classifiers/svm.py

Added some comments in svm.py + a computation of svm objective is rearranged to look more like a formula for objective fun on page 42 of the tutorial.

Some comments added and computation of the svm objective is rearranged

---

labs/notebooks/sequence_models/Exercises_2.1_to_2.11.ipynb
lxmls/sequences/sequence_classification_decoder.py
lxmls/sequences/structured_perceptron.py

Some comments added to `structured_perceptron.py` and `sequence_classification_decoder.py` + Some typos fixed in a notebook Exercises_2.1_to_2.11.

Some comments added

---

solve.py

- replaced urllib2 with urllib
- added brackets for print

Made solve.py Python3-compatible

---

labs/notebooks/basic_tutorials/Exercises_0.10_to_0.15.ipynb

unfixing buggy (student)

---

labs/notebooks/sequence_models/Exercises_2.1_to_2.11.ipynb

(Also, I deleted all cell outputs.)

Deleting solutions on student branch

---

labs/notebooks/basic_tutorials/Exercises_0.10_to_0.14.ipynb

Update of Ex. 0.xx for student

---

README.md
labs/notebooks/basic_tutorials/Exercises_0.10_to_0.14.ipynb

The error being calculated in this cell was using the initialization values of the parameters, rather than the optimized.

error being printed used the wrong parameters

---

LICENSE.txt

I think it's time to introduce a copyright owner in the license

ENH: copyright owner

---

labs/notebooks/basic_tutorials/python_basics.ipynb
labs/notebooks/learning_structured_predictors/exercise_1.ipynb
labs/notebooks/learning_structured_predictors/exercise_2.ipynb
labs/notebooks/learning_structured_predictors/exercise_3.ipynb
labs/notebooks/learning_structured_predictors/exercise_4.ipynb
labs/notebooks/linear_classifiers/exercises.ipynb
labs/notebooks/non_linear_classifiers/exercise_1.ipynb
labs/notebooks/non_linear_classifiers/exercise_2.ipynb
labs/notebooks/non_linear_classifiers/exercise_3.ipynb
labs/notebooks/non_linear_classifiers/exercise_4.ipynb
labs/notebooks/non_linear_sequence_classifiers/exercise_2.ipynb
labs/notebooks/parsing/exercise_3.ipynb

All kernels in notebooks now are default Python 3.

ENH: uniform kernels [student branch]

---

labs/notebooks/basic_tutorials/Exercises_0.10_to_0.14.ipynb

Just as #113 , but applied to the master branch.

style improvements

---

labs/notebooks/basic_tutorials/python_basics.ipynb
labs/notebooks/learning_structured_predictors/exercise_1.ipynb
labs/notebooks/learning_structured_predictors/exercise_2.ipynb
labs/notebooks/learning_structured_predictors/exercise_3.ipynb
labs/notebooks/learning_structured_predictors/exercise_4.ipynb
labs/notebooks/linear_classifiers/exercises.ipynb
labs/notebooks/non_linear_classifiers/exercise_1.ipynb
labs/notebooks/non_linear_classifiers/exercise_2.ipynb
labs/notebooks/non_linear_classifiers/exercise_3.ipynb
labs/notebooks/non_linear_classifiers/exercise_4.ipynb
labs/notebooks/non_linear_sequence_classifiers/exercise_2.ipynb
labs/notebooks/parsing/exercise_3.ipynb

All kernels in notebooks now are default Python 3.

ENH: uniform kernels

---

labs/notebooks/reinforcement_learning/exercises_1_4.ipynb

Commits:
1. Fix exercise 6.1 description, it's confusing:
gamma is discount rate, not learning rate
these are different things
learning rate is alpha, there is no learning rate in Policy Evaluation
2. Fix in import in exercises_1_4.ipynb

Updates for RL

---

labs/notebooks/reinforcement_learning/exercise_1_3_solutions.ipynb
labs/notebooks/reinforcement_learning/exercises_1_4.ipynb

Fix mention of "learning rate" to refer to "discount factor"

---

.travis.yml
tests/test_galton_dataset.py
tests/test_linear_classifier.py
tests/test_non_linear_classifiers_numpy.py
tests/test_non_linear_classifiers_pytorch.py
tests/test_parsing.py
tests/test_sequence_models.py
tests/test_sequence_models_deep_learning.py
tests/test_structured_predictors.py
tox.ini

Fix TravisCI configuration that was also specifying the PyTorch version (see #135) and speed tests a bit, by making some methods run fewer epochs and also by parallelizing pytest.

Pytorch 0.1.0

---

.gitignore
.travis.yml
lxmls/deep_learning/pytorch_models/rnn.py
requirements.txt
tests/test_galton_dataset.py
tests/test_linear_classifier.py
tests/test_non_linear_classifiers_numpy.py
tests/test_non_linear_classifiers_pytorch.py
tests/test_parsing.py
tests/test_sequence_models.py
tests/test_sequence_models_deep_learning.py
tests/test_structured_predictors.py
tox.ini

- Solves https://github.com/LxMLS/lxmls-toolkit/issues/135 by importing Categorical in another (less elegant) way.
- Also upgrades pytorch to 1.0.0 (torchvision 0.2.2)
- minor changes in the PolcyRNN for PEP (still needs general code review)

Pytorch 1.0.0 and passes Travis

---

labs/notebooks/basic_tutorials/Exercises_0.10_to_0.14.ipynb

not needed, causing py/py3 problems

Remove iteration in gradient toy problem

---

labs/notebooks/basic_tutorials/Exercises_0.10_to_0.14.ipynb

I've checked, apparently no other notebooks have the same issue.

Replaced unknown character by actual minus sign

---

lxmls/classifiers/mira.py
tests/test_linear_classifier.py

Float division for stepsize computaton in Mira

---

labs/notebooks/learning_structured_predictors/exercise_2.ipynb
labs/notebooks/linear_classifiers/exercises.ipynb
labs/notebooks/non_linear_sequence_classifiers/exercise_1.ipynb

Fixed small typos and formatting issues

---

lxmls/reinforcement_learning/score_function_estimator.py

gradient accumulation doesn't make sense here, although the code was working. Without grad accumulation, the learning rate was too low, so I also fixed that

stop gradient accumulation; increase learning rate

---

labs/notebooks/linear_classifiers/exercises.ipynb

delete extra SVM plot

---

labs/notebooks/non_linear_classifiers/exercise_2.ipynb

Sequence and Non-linear days were swapped in guide book recently, so here we update index of algorithm in notebook description

Small fix in non-linear exercise description

---

labs/notebooks/non_linear_classifiers/exercise_1.ipynb

Just to remove the comments (which are the solutions) from exercise 1.

Remove comments (solution) from exercise 1

---

setup.py

This should fix it.
However, we should stop using pip's internals for this.

quick n dirty fix for #169

---

lxmls/transformers/model.py

Added the final code of CausalAttention in model.py

modified/tested causal-attention module

---

lxmls/transformers/model.py
lxmls/transformers/pretrained_attention.py

Hacky fix to loading the attention module

hacky pretrained weights

---

labs/notebooks/transformers/exercises_answers.ipynb

I'm adding a more intuitive testing for cross attention and some hint for the matrix dimensions

Cross Attention test fix

---

README.md

See my comments on https://github.com/LxMLS/lxmls-toolkit/issues/195
Also see sister PR https://github.com/LxMLS/lxmls-guide/pull/151

Update README with simpler instructions for install

---

README.md

Updating the readme on master, removing dev tools, adding windows installation instructions.

Updating readme on master
